-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id integer NOT NULL DEFAULT nextval('activity_logs_id_seq'::regclass),
  action character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id integer,
  user_id integer NOT NULL,
  organization_id integer,
  description text NOT NULL,
  details jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.contacts (
  id bigint NOT NULL DEFAULT nextval('contacts_id_seq'::regclass),
  organization_id bigint NOT NULL,
  contact_type character varying DEFAULT 'company'::character varying,
  name character varying NOT NULL,
  email character varying,
  phone character varying,
  address_line character varying,
  postal_code character varying,
  city character varying,
  country character varying DEFAULT 'Denmark'::character varying,
  vat_number character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.invoice_items (
  id bigint NOT NULL DEFAULT nextval('invoice_items_id_seq'::regclass),
  invoice_id bigint NOT NULL,
  description text NOT NULL,
  quantity numeric DEFAULT 1,
  unit character varying DEFAULT 'pcs'::character varying,
  unit_price numeric DEFAULT 0,
  discount numeric DEFAULT 0,
  line_total numeric DEFAULT ((quantity * unit_price) * ((1)::numeric - (discount / (100)::numeric))),
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
create table public.invoices (
  id bigserial not null,
  organization_id bigint not null,
  contact_id bigint null,
  created_by bigint null,
  invoice_number serial not null,
  issue_date date not null default CURRENT_DATE,
  due_date date null,
  payment_terms character varying(100) null default 'Net 8 days'::character varying,
  status character varying(50) null default 'draft'::character varying,
  comments text null,
  subtotal numeric(12, 2) null default 0,
  discount_total numeric(12, 2) null default 0,
  tax_total numeric(12, 2) null default 0,
  total_amount numeric(12, 2) null default 0,
  currency character varying(10) null default 'DKK'::character varying,
  bank_reg_no character varying(50) null,
  bank_account_no character varying(50) null,
  interest_rate numeric(5, 2) null default 0.81,
  late_fee numeric(12, 2) null default 100.00,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  is_published boolean null default false,
  payment_link text null,
  constraint invoices_pkey primary key (id),
  constraint invoices_contact_id_fkey foreign KEY (contact_id) references contacts (id) on delete set null,
  constraint invoices_created_by_fkey foreign KEY (created_by) references users (id) on delete set null,
  constraint invoices_organization_id_fkey foreign KEY (organization_id) references organizations (id) on delete CASCADE
) TABLESPACE pg_default;
CREATE TABLE public.organizations (
  id bigint NOT NULL DEFAULT nextval('organizations_id_seq'::regclass),
  created_by bigint NOT NULL,
  business_type character varying NOT NULL,
  company_name character varying NOT NULL,
  address_line character varying,
  postal_code character varying,
  city character varying,
  country character varying DEFAULT 'Denmark'::character varying,
  email character varying,
  attention_person character varying,
  vat_number character varying,
  currency character varying DEFAULT 'DKK'::character varying,
  status character varying DEFAULT 'active'::character varying,
  subscription_plan character varying DEFAULT 'free'::character varying,
  data_processing_agreement boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  logo text,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.products (
  id bigint NOT NULL DEFAULT nextval('products_id_seq'::regclass),
  organization_id bigint NOT NULL,
  name text NOT NULL,
  product_code text,
  quantity numeric NOT NULL DEFAULT 1,
  unit text,
  price_excl_vat numeric NOT NULL DEFAULT 0,
  account_code text NOT NULL CHECK (account_code = ANY (ARRAY['1000'::text, '1010'::text, '1100'::text, '1110'::text, '1120'::text, '1130'::text, '1200'::text, '1210'::text, '1220'::text, '1230'::text, '9000'::text, '9010'::text])),
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.purchase_lines (
  id bigint NOT NULL DEFAULT nextval('purchase_lines_id_seq'::regclass),
  purchase_id bigint NOT NULL,
  line_no integer NOT NULL CHECK (line_no > 0),
  description text NOT NULL,
  amount_incl_vat numeric NOT NULL CHECK (amount_incl_vat >= 0::numeric),
  vat_amount numeric NOT NULL DEFAULT 0 CHECK (vat_amount >= 0::numeric),
  account_code character varying,
  inventory_category character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_lines_pkey PRIMARY KEY (id),
  CONSTRAINT fk_purchase_lines_purchase_id FOREIGN KEY (purchase_id) REFERENCES public.purchases(id)
);
CREATE TABLE public.purchases (
  id bigint NOT NULL DEFAULT nextval('purchases_id_seq'::regclass),
  organization_id bigint NOT NULL,
  supplier_name text NOT NULL,
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['cash'::text, 'credit'::text])),
  attachment_date date NOT NULL,
  inventory_category text,
  account_code text,
  description text,
  amount_incl_vat numeric NOT NULL DEFAULT 0,
  vat_amount numeric NOT NULL DEFAULT 0,
  subtotal numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text])),
  attachment_url text,
  attachment_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchases_pkey PRIMARY KEY (id),
  CONSTRAINT purchases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.users (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  full_name character varying DEFAULT ''::character varying,
  email character varying DEFAULT ''::character varying,
  role character varying DEFAULT 'owner'::character varying,
  password text,
  istwofactor boolean,
  otp numeric,
  otp_expiry timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);